package Application.Controllers;

import Application.DAOs.UserDAO;
import Application.Model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@CrossOrigin
@RestController
@RequestMapping("/User") // This means URL's start with /Usuarios (after Application path)
public class SearchController {
    @Autowired // This means to get the bean called UserDAOImpl
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserDAO userDAO;


    @RequestMapping(method = RequestMethod.GET)
    public Iterable<User> getUserByName(String name) {
        return userDAO.getFirstNamesLike(name);
    }

    @RequestMapping(method = RequestMethod.GET)
    public Iterable<User> getUserByLastName(String lastName) {
        return userDAO.getUsersByLastName(lastName);
    }

    @RequestMapping(method = RequestMethod.GET)
    public Iterable<User> getUserBySport(String sport) {
        return userDAO.getUsersByDeportesLike(sport);
    }
}
